import { photos } from "@/lib/images";
import type { SeedProperty } from "./seed-data";

/**
 * Additional realistic marketplace inventory in the style of popular Pakistani
 * portals (Zameen-style plots, houses and rentals across DHA, Bahria, Lake
 * City and scheme areas). All copy is original demo content.
 */
export const extraPropertySeed: SeedProperty[] = [
  {
    slug: "5-marla-house-dha-phase-9-town-lahore",
    title: "5 Marla Brand New Designer House",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 9 Town",
    address: "Block D, DHA Phase 9 Town, Lahore",
    lat: 31.4215,
    lng: 74.4702,
    price: 16_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Brand new 5 Marla designer house in DHA Phase 9 Town with solid grey structure, Spanish tile roofing elevation and a proper mumty. Ground floor has drawing, dining and kitchen while the first floor carries two bedrooms with attached baths and a terrace.",
    features: [
      "Solid Awwal-grade construction",
      "Spanish elevation with tile work",
      "Powder room on ground floor",
      "Imported sanitary fittings",
      "Wiring for split ACs in all rooms",
    ],
    amenities: ["Gated society", "24/7 security", "Carpeted roads", "Nearby commercial", "Mosque nearby"],
    images: [photos.villas[5], photos.interiors[5], photos.bedrooms[6], photos.bedrooms[7], photos.interiors[1]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1920,
    daysAgo: 2,
  },
  {
    slug: "10-marla-house-bahria-orchard-phase-4-lahore",
    title: "10 Marla Corner House Near Gate",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Bahria Orchard Phase 4",
    address: "Block G-5, Bahria Orchard Phase 4, Lahore",
    lat: 31.3618,
    lng: 74.1994,
    price: 23_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Well-built 10 Marla corner house close to the Phase 4 gate in Bahria Orchard. Extra land on the side gives a bigger lawn, and the street is fully populated with families. Ideal for buyers who want Bahria facilities at an Orchard budget.",
    features: [
      "Corner plot with extra lawn",
      "Walking distance to gate and commercial",
      "Three-storey with mumty",
      "Separate servant quarter",
      "Bore plus Bahria water connection",
    ],
    amenities: ["Gated community", "Theme park nearby", "School and hospital", "Backup power", "Security patrol"],
    images: [photos.villas[4], photos.interiors[4], photos.bedrooms[5], photos.bedrooms[6], photos.interiors[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1340,
    daysAgo: 4,
  },
  {
    slug: "1-kanal-plot-file-dha-phase-10-lahore",
    title: "1 Kanal Affidavit File in DHA Phase 10",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 10",
    address: "DHA Phase 10, Lahore",
    lat: 31.4021,
    lng: 74.5233,
    price: 10_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 0,
    furnishing: "Not applicable",
    possession: "File",
    description:
      "1 Kanal affidavit file in DHA Phase 10 with complete documents and paid instalments. Verification available from the DHA office before token. Suitable for medium-term investors waiting for ballot and development announcements.",
    features: [
      "Complete file with receipts",
      "Instalments paid up to date",
      "Verification before token",
      "Clear seller title",
    ],
    amenities: ["DHA transfer procedure", "Escrow-friendly deal", "Documentation support"],
    images: [photos.dev[3], photos.dev[5], photos.dev[6], photos.dev[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 2210,
    daysAgo: 5,
  },
  {
    slug: "5-marla-possession-plot-lake-city-m7-lahore",
    title: "5 Marla Possession Plot in Lake City M-7",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Lake City",
    address: "Sector M-7, Lake City, Lahore",
    lat: 31.3524,
    lng: 74.2611,
    price: 9_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "Possession-ready 5 Marla plot in Lake City Sector M-7 on a 30-foot road near the park. All dues cleared with possession letter in hand. Surrounding streets are populated, so construction can start immediately.",
    features: [
      "Possession with allotment letter",
      "30-foot front road",
      "Near park and mosque",
      "All dues cleared",
    ],
    amenities: ["Gated community", "Golf course nearby", "Schools and commercial", "24/7 security"],
    images: [photos.dev[5], photos.dev[1], photos.dev[0], photos.dev[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1680,
    daysAgo: 6,
  },
  {
    slug: "2-bed-apartment-bahria-enclave-islamabad",
    title: "2 Bed Apartment with Margalla View",
    purpose: "buy",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Bahria Enclave",
    address: "Sector H, Bahria Enclave, Islamabad",
    lat: 33.6312,
    lng: 73.2218,
    price: 13_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    areaValue: 1100,
    areaUnit: "sqft",
    areaSqft: 1100,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Sunny 2-bedroom apartment in Bahria Enclave with a Margalla-facing balcony. The building has two lifts, standby generators and dedicated visitor parking. Popular with young families and Bahria Head Office staff.",
    features: [
      "Margalla-facing balcony",
      "Two lifts in building",
      "Standby generator backup",
      "Dedicated parking bay",
    ],
    amenities: ["Gated sector", "Cineplex and zoo nearby", "Jamia mosque", "Maintenance staff"],
    images: [photos.interiors[3], photos.bedrooms[1], photos.interiors[6], photos.bedrooms[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1210,
    daysAgo: 7,
  },
  {
    slug: "10-marla-house-g13-islamabad",
    title: "10 Marla Solid House in G-13",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "G-13",
    address: "G-13/2, Islamabad",
    lat: 33.6618,
    lng: 72.9923,
    price: 46_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 6,
    bathrooms: 6,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Solid 10 Marla double-storey house in G-13/2 with six bedrooms and a proper basement. The sector is fully developed with markets, schools and direct Kashmir Highway access. Documents complete with CDA transfer record.",
    features: [
      "Usable basement",
      "Six bedrooms with attached baths",
      "Two kitchens",
      "CDA sector with clear record",
    ],
    amenities: ["Developed sector", "Markets and schools", "Highway access", "Water and gas"],
    images: [photos.villas[6], photos.interiors[1], photos.bedrooms[3], photos.bedrooms[2], photos.interiors[9]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 990,
    daysAgo: 9,
  },
  {
    slug: "3-bed-flat-gulistan-johar-karachi-rent",
    title: "3 Bed Flat for Rent in Gulistan-e-Johar",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Gulistan-e-Johar",
    address: "Block 12, Gulistan-e-Johar, Karachi",
    lat: 24.9204,
    lng: 67.1322,
    price: 55_000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 3,
    bathrooms: 2,
    areaValue: 1350,
    areaUnit: "sqft",
    areaSqft: 1350,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Ventilated 3-bedroom flat on the second floor in Gulistan-e-Johar Block 12. West-open with boundary-wall project, sweet water and standby generator for common areas. Close to universities, hospitals and main Rashid Minhas Road.",
    features: [
      "West-open ventilated flat",
      "Boundary-wall project",
      "Sweet water supply",
      "Generator for common areas",
    ],
    amenities: ["Lift", "Security guard", "Nearby universities", "Market at walking distance"],
    images: [photos.bedrooms[5], photos.interiors[1], photos.bedrooms[3], photos.interiors[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1730,
    daysAgo: 3,
  },
  {
    slug: "120-sqyd-house-scheme-33-karachi",
    title: "120 Sq Yd Single-Storey House in Scheme 33",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Scheme 33",
    address: "Sector 35-A, Scheme 33, Karachi",
    lat: 24.9518,
    lng: 67.1834,
    price: 19_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1080,
    areaUnit: "sqft",
    areaSqft: 1080,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Single-storey 120 sq yard house in Scheme 33 Sector 35-A with leased documents. Strong structure with an RCC roof that can take another floor. The lane is populated and minutes from the M-9 link and main Superhighway.",
    features: [
      "Leased with complete documents",
      "RCC roof, second floor possible",
      "Populated lane",
      "Near M-9 link road",
    ],
    amenities: ["Water and electricity", "Nearby schools", "Masjid in street", "Public transport"],
    images: [photos.villas[2], photos.interiors[0], photos.bedrooms[5], photos.bedrooms[3]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1440,
    daysAgo: 8,
  },
  {
    slug: "8-marla-commercial-plot-bahria-phase-8-rawalpindi",
    title: "8 Marla Commercial Plot on Main Boulevard",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "rawalpindi",
    cityName: "Rawalpindi",
    locationArea: "Bahria Town Phase 8",
    address: "Business District, Bahria Town Phase 8, Rawalpindi",
    lat: 33.5124,
    lng: 73.1042,
    price: 42_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 8,
    areaUnit: "marla",
    areaSqft: 1800,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "8 Marla commercial plot facing the Business District boulevard in Bahria Town Phase 8. High-visibility location suited for a bank branch, retail outlet or clinic. Possession plot with numbers allotted.",
    features: [
      "Boulevard-facing commercial",
      "Possession plot, numbers allotted",
      "High footfall district",
      "Wide frontage",
    ],
    amenities: ["Business district", "Ample parking", "Security", "Nearby residential sectors"],
    images: [photos.dev[1], photos.dev[0], photos.dev[5]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 720,
    daysAgo: 12,
  },
  {
    slug: "5-marla-house-wapda-city-faisalabad",
    title: "5 Marla House in Wapda City",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "faisalabad",
    cityName: "Faisalabad",
    locationArea: "Wapda City",
    address: "Block B, Wapda City, Faisalabad",
    lat: 31.4022,
    lng: 73.0218,
    price: 11_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 3,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Neat 5 Marla double-storey house in Wapda City Block B. Four bedrooms with tiled flooring, a proper kitchen with cabinets and a mumty store. The block is fully populated with underground electrification.",
    features: [
      "Four bedrooms, three baths",
      "Fitted kitchen cabinets",
      "Underground electrification",
      "Populated block",
    ],
    amenities: ["Gated society", "Parks", "Carpeted roads", "Nearby schools"],
    images: [photos.villas[9], photos.interiors[4], photos.bedrooms[0], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 610,
    daysAgo: 14,
  },
  {
    slug: "10-marla-house-bosan-road-multan-rent",
    title: "10 Marla Upper Portion for Rent on Bosan Road",
    purpose: "rent",
    category: "apartment",
    propertyType: "Upper Portion",
    citySlug: "multan",
    cityName: "Multan",
    locationArea: "Bosan Road",
    address: "Officers Colony, Bosan Road, Multan",
    lat: 30.1931,
    lng: 71.4932,
    price: 70_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1600,
    areaUnit: "sqft",
    areaSqft: 1600,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Independent 10 Marla upper portion on Bosan Road with a separate gate and separate meters. Three bedrooms with attached baths, a large terrace and a separate laundry area. Preferred for bank officers and medical professionals.",
    features: [
      "Separate gate and entrance",
      "Separate electricity and gas meters",
      "Large terrace",
      "Separate laundry area",
    ],
    amenities: ["Secure street", "Near hospitals", "Backup power", "Nearby market"],
    images: [photos.interiors[6], photos.bedrooms[2], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 540,
    daysAgo: 10,
  },
  {
    slug: "1-kanal-farmhouse-bedian-road-lahore-rent",
    title: "1 Kanal Farmhouse for Rent on Bedian Road",
    purpose: "rent",
    category: "farmhouse",
    propertyType: "Farmhouse",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Bedian Road",
    address: "Bedian Road, near DHA Phase 6, Lahore",
    lat: 31.4733,
    lng: 74.4618,
    price: 350_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 6,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Lush 1 Kanal farmhouse on Bedian Road available for long-term rent. Four bedrooms, a swimming pool, servant quarter and a mango orchard boundary. Suitable for executives, farm stays and corporate retreats.",
    features: [
      "Swimming pool with deck",
      "Mango orchard boundary",
      "Servant quarter",
      "Corporate retreat friendly",
    ],
    amenities: ["Farmhouse community", "Security patrol", "Green surroundings", "Wide access road"],
    images: [photos.villas[3], photos.villas[9], photos.interiors[8], photos.bedrooms[4], photos.villas[1]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 880,
    daysAgo: 11,
  },
];
