import { photo, photos } from "@/lib/images";

const p = photo;

export const citySeed = [
  {
    slug: "lahore",
    name: "Lahore",
    province: "Punjab",
    tagline: "Pakistan's most liquid property market",
    description:
      "From DHA and Bahria Town to Gulberg and Johar Town, Lahore offers the widest spread of residential and commercial inventory in Pakistan — with deep resale activity and strong rental demand.",
    imageUrl: p(photos.cities.lahore, 1000, 750),
    imageAlt: "Historic Mughal-era architecture in Lahore, Pakistan",
    lat: 31.5204,
    lng: 74.3587,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    slug: "islamabad",
    name: "Islamabad",
    province: "Islamabad Capital Territory",
    tagline: "Capital living with planned infrastructure",
    description:
      "Islamabad combines sector-based planning, embassy enclaves and premium new developments. DHA, Bahria Enclave and Gulberg Greens drive the highest-value transactions in the capital.",
    imageUrl: p(photos.cities.islamabad, 1000, 750),
    imageAlt: "Faisal Mosque and Islamabad skyline at sunset",
    lat: 33.6844,
    lng: 73.0479,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    slug: "karachi",
    name: "Karachi",
    province: "Sindh",
    tagline: "Where business meets high-rise living",
    description:
      "Karachi's market is dominated by apartment towers, commercial plazas and coastal developments in DHA, Clifton and Bahria Town. Rental yields for offices lead the country.",
    imageUrl: p(photos.cities.karachi, 1000, 750),
    imageAlt: "Karachi skyline at sunset with high-rise buildings",
    lat: 24.8607,
    lng: 67.0011,
    isFeatured: true,
    sortOrder: 3,
  },
  {
    slug: "rawalpindi",
    name: "Rawalpindi",
    province: "Punjab",
    tagline: "Islamabad's connected twin city",
    description:
      "Rawalpindi gives buyers Islamabad access at a lower entry point. Bahria Town, Gulraiz and Askari schemes remain the strongest performers for family housing and rentals.",
    imageUrl: p(photos.cities.rawalpindi, 1000, 750),
    imageAlt: "Green hills and roads around Rawalpindi and the Murree expressway",
    lat: 33.5651,
    lng: 73.0169,
    isFeatured: true,
    sortOrder: 4,
  },
  {
    slug: "faisalabad",
    name: "Faisalabad",
    province: "Punjab",
    tagline: "Industrial strength, growing housing demand",
    description:
      "Textile wealth keeps Faisalabad's housing market active. Eden Valley, Wapda City and D-Ground attract both end users and long-term investors.",
    imageUrl: p(photos.cities.faisalabad, 1000, 750),
    imageAlt: "Aerial view of an expanding urban development",
    lat: 31.4187,
    lng: 73.0791,
    isFeatured: true,
    sortOrder: 5,
  },
  {
    slug: "multan",
    name: "Multan",
    province: "Punjab",
    tagline: "Southern Punjab's fastest maturing market",
    description:
      "Multan's new societies such as Buch Villas and DHA Multan are reshaping the city's housing map, with strong demand for plots and modern villas.",
    imageUrl: p(photos.cities.multan, 1000, 750),
    imageAlt: "Heritage architecture reflecting Multan's property market",
    lat: 30.1575,
    lng: 71.5249,
    isFeatured: true,
    sortOrder: 6,
  },
  {
    slug: "gujranwala",
    name: "Gujranwala",
    province: "Punjab",
    tagline: "Solid family housing market",
    description:
      "Gujranwala's Satellite Town, Wapda Town and Master City offer affordable houses and plots for families commuting between Lahore and the industrial belt.",
    imageUrl: p(photos.cities.gujranwala, 1000, 750),
    imageAlt: "Busy urban street scene in Punjab, Pakistan",
    lat: 32.1877,
    lng: 74.1945,
    isFeatured: false,
    sortOrder: 7,
  },
  {
    slug: "peshawar",
    name: "Peshawar",
    province: "Khyber Pakhtunkhwa",
    tagline: "Renewed demand for secure schemes",
    description:
      "Hayatabad, Regi Model Town and University Town lead Peshawar's demand, with buyers prioritising gated security and ready infrastructure.",
    imageUrl: p(photos.cities.peshawar, 1000, 750),
    imageAlt: "Evening city lights along a Peshawar street",
    lat: 34.0151,
    lng: 71.5249,
    isFeatured: false,
    sortOrder: 8,
  },
];

export const agentSeed = [
  {
    slug: "hassan-rizvi",
    name: "Hassan Rizvi",
    title: "Senior Property Consultant",
    agency: "Pak Property Partners — Lahore",
    email: "hassan.rizvi@propertywx.pk",
    phone: "+92 300 1234567",
    whatsapp: "923001234567",
    cityName: "Lahore",
    experienceYears: 11,
    dealsClosed: 340,
    languages: ["English", "Urdu", "Punjabi"],
    bio: "Specialises in DHA, Bahria Town and Gulberg residential deals for overseas Pakistani buyers and families relocating to Lahore.",
  },
  {
    slug: "ayesha-noor",
    name: "Ayesha Noor",
    title: "Investment Advisor",
    agency: "Pak Property Partners — Islamabad",
    email: "ayesha.noor@propertywx.pk",
    phone: "+92 301 7654321",
    whatsapp: "923017654321",
    cityName: "Islamabad",
    experienceYears: 9,
    dealsClosed: 215,
    languages: ["English", "Urdu"],
    bio: "Guides investors through DHA Islamabad and Bahria Enclave allocations, with a focus on rental yield and off-plan payments.",
  },
  {
    slug: "bilal-shaikh",
    name: "Bilal Shaikh",
    title: "Commercial Leasing Lead",
    agency: "Pak Property Partners — Karachi",
    email: "bilal.shaikh@propertywx.pk",
    phone: "+92 321 5566778",
    whatsapp: "923215566778",
    cityName: "Karachi",
    experienceYears: 12,
    dealsClosed: 268,
    languages: ["English", "Urdu", "Sindhi"],
    bio: "Handles office, retail and warehouse requirements across Clifton, DHA and Shahrah-e-Faisal for corporate tenants.",
  },
  {
    slug: "sana-ali",
    name: "Sana Ali",
    title: "Residential Sales Manager",
    agency: "Pak Property Partners — Multan",
    email: "sana.ali@propertywx.pk",
    phone: "+92 333 4455667",
    whatsapp: "923334455667",
    cityName: "Multan",
    experienceYears: 7,
    dealsClosed: 158,
    languages: ["English", "Urdu", "Saraiki"],
    bio: "Advises first-time buyers in South Punjab on plot files, possession timelines and society development status.",
  },
];

export type SeedProperty = {
  slug: string;
  title: string;
  purpose: "buy" | "rent";
  category: string;
  propertyType: string;
  citySlug: string;
  cityName: string;
  locationArea: string;
  address: string;
  lat: number;
  lng: number;
  price: number;
  priceUnit: "total" | "month";
  negotiable: boolean;
  bedrooms: number;
  bathrooms: number;
  areaValue: number;
  areaUnit: "sqft" | "marla" | "kanal";
  areaSqft: number;
  parking: number;
  furnishing: string;
  possession: string;
  description: string;
  features: string[];
  amenities: string[];
  images: number[];
  featured: boolean;
  verified: boolean;
  isNewProject: boolean;
  projectSlug?: string;
  agentSlug: string;
  views: number;
  daysAgo: number;
};

export const propertySeed: SeedProperty[] = [
  {
    slug: "modern-luxury-villa-dha-phase-5-lahore",
    title: "Modern Luxury Villa with Basement",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 5",
    address: "Block L, DHA Phase 5, Lahore",
    lat: 31.4697,
    lng: 74.4116,
    price: 125_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 5500,
    areaUnit: "sqft",
    areaSqft: 5500,
    parking: 3,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A contemporary 1 Kanal villa on a quiet DHA Phase 5 street, designed around a double-height entrance, a full basement and an open-plan kitchen with imported fittings. The rear terrace opens onto a landscaped lawn with provision for a plunge pool.",
    features: [
      "Full basement with home theatre",
      "Imported Italian marble flooring",
      "Open-plan kitchen with island",
      "Servant quarters with separate entrance",
      "Solar-ready wiring with net metering",
      "Double-glazed windows throughout",
    ],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Backup power", "Wide carpeted roads"],
    images: [photos.villas[0], photos.interiors[0], photos.bedrooms[1], photos.interiors[3], photos.villas[8], photos.bedrooms[4]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 2840,
    daysAgo: 3,
  },
  {
    slug: "luxury-apartment-bahria-town-karachi-rent",
    title: "Luxury Sea-Breeze Apartment",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Bahria Town Karachi",
    address: "Precinct 10A, Bahria Town Karachi",
    lat: 25.0007,
    lng: 67.3142,
    price: 280_000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 3,
    bathrooms: 4,
    areaValue: 2400,
    areaUnit: "sqft",
    areaSqft: 2400,
    parking: 2,
    furnishing: "Fully furnished",
    possession: "Available",
    description:
      "Fully furnished 3-bedroom apartment in a serviced tower with panoramic views, community pool and direct lift access. Ideal for corporate tenants and senior executives on assignment in Karachi.",
    features: [
      "Fully furnished with premium appliances",
      "Community pool and gym access",
      "Covered parking for two cars",
      "Standby generator for full load",
      "Concierge and visitor management",
    ],
    amenities: ["Swimming pool", "Gym", "Concierge", "Elevator", "CCTV coverage"],
    images: [photos.interiors[9], photos.bedrooms[0], photos.interiors[6], photos.bedrooms[7], photos.interiors[1]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1930,
    daysAgo: 6,
  },
  {
    slug: "the-grand-residences-islamabad",
    title: "The Grand Residences — Luxury Residence",
    purpose: "buy",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 2",
    address: "Sector F, DHA Phase 2, Islamabad",
    lat: 33.532,
    lng: 73.1496,
    price: 19_000_000,
    priceUnit: "total",
    negotiable: false,
    bedrooms: 2,
    bathrooms: 3,
    areaValue: 1450,
    areaUnit: "sqft",
    areaSqft: 1450,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Booking open",
    description:
      "A two-bedroom unit in The Grand Residences, a gated tower community with landscaped courtyards, residents' club and uninterrupted Margalla views. Payment plans are structured over 36 monthly instalments.",
    features: [
      "Margalla Hills views from upper floors",
      "36-month instalment plan available",
      "Residents' club and community lawn",
      "High-speed lifts and standby power",
      "Smart access control for residents",
    ],
    amenities: ["Gated tower", "Security staff", "Club house", "Backup power", "Retail arcade"],
    images: [photos.interiors[7], photos.bedrooms[2], photos.interiors[5], photos.bedrooms[3], photos.interiors[2]],
    featured: true,
    verified: true,
    isNewProject: true,
    projectSlug: "the-grand-residences",
    agentSlug: "ayesha-noor",
    views: 3120,
    daysAgo: 2,
  },
  {
    slug: "premium-office-space-gulberg-lahore",
    title: "Premium Corporate Office Floor",
    purpose: "buy",
    category: "office",
    propertyType: "Office",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Gulberg III",
    address: "Main Boulevard, Gulberg III, Lahore",
    lat: 31.5204,
    lng: 74.3587,
    price: 450_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 4,
    areaValue: 8000,
    areaUnit: "sqft",
    areaSqft: 8000,
    parking: 14,
    furnishing: "Fitted",
    possession: "Available",
    description:
      "An entire upper floor in a dedicated corporate building on Main Boulevard Gulberg, already fitted with a reception, two conference rooms and an open workspace for 70 desks. Suitable for head offices and BPO operations.",
    features: [
      "Fitted floor with cabling and HVAC",
      "Two conference rooms and board room",
      "14 dedicated parking bays",
      "Two passenger lifts plus service lift",
      "Dedicated 200 KVA connection",
    ],
    amenities: ["Main boulevard frontage", "Backup generator", "24/7 building security", "Fire safety system"],
    images: [photos.commercial[0], photos.commercial[9], photos.commercial[3], photos.commercial[5], photos.commercial[7]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1480,
    daysAgo: 9,
  },
  {
    slug: "10-marla-brand-new-house-dha-phase-2-lahore",
    title: "Brand New 10 Marla Designer House",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 2",
    address: "Block G, DHA Phase 2, Lahore",
    lat: 31.4897,
    lng: 74.3956,
    price: 62_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Freshly completed 10 Marla house with three floors, a proper drawing and dining separation, and a rooftop laundry. Located minutes from DHA Phase 2's main commercial and school belt.",
    features: [
      "Three functional floors plus terrace",
      "Separate drawing and dining areas",
      "Wooden flooring in bedrooms",
      "Rooftop laundry and water storage",
      "Security grills on all openings",
    ],
    amenities: ["Gated society", "Park at walking distance", "Backup power", "Carpeted roads"],
    images: [photos.villas[4], photos.interiors[4], photos.bedrooms[5], photos.bedrooms[6], photos.interiors[0]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 2210,
    daysAgo: 5,
  },
  {
    slug: "1-kanal-farmhouse-gulberg-greens-islamabad",
    title: "1 Kanal Farmhouse with Orchard Lawn",
    purpose: "buy",
    category: "farmhouse",
    propertyType: "Farmhouse",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Gulberg Greens",
    address: "Gulberg Greens, Islamabad",
    lat: 33.6102,
    lng: 73.1101,
    price: 155_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 3700,
    parking: 6,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A private farmhouse retreat with mature orchard trees, a guest annex and a covered outdoor dining pavilion. Suited to families wanting weekend space within easy reach of Islamabad's sectors.",
    features: [
      "Mature fruit orchard and lawn",
      "Covered outdoor dining pavilion",
      "Separate guest annex with bath",
      "Bore well with filtration",
      "Boundary wall with gated entry",
    ],
    amenities: ["Farmhouse community", "Security patrol", "Green surroundings", "Wide access road"],
    images: [photos.villas[3], photos.villas[9], photos.interiors[8], photos.bedrooms[4], photos.villas[1]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1180,
    daysAgo: 11,
  },
  {
    slug: "10-marla-residential-plot-bahria-town-lahore",
    title: "10 Marla Residential Plot — Prime Location",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Bahria Town Lahore",
    address: "Sector E, Bahria Town Lahore",
    lat: 31.3627,
    lng: 74.184,
    price: 19_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "Level, ready-for-construction plot on a 40-foot road in Bahria Town Lahore with all utilities laid and development charges cleared. Clear transfer, ready for immediate file movement.",
    features: [
      "40-foot front road",
      "All dues cleared, transfer ready",
      "Corner-adjacent open on one side",
      "Level ground, no filling required",
    ],
    amenities: ["Gated community", "Utilities laid", "Parks and mosque nearby", "Possession ready"],
    images: [photos.dev[3], photos.dev[5], photos.dev[6], photos.dev[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 3410,
    daysAgo: 4,
  },
  {
    slug: "3-bed-apartment-dha-phase-6-karachi",
    title: "Three-Bed Family Apartment with Balcony",
    purpose: "buy",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 6",
    address: "Khayaban-e-Bukhari, DHA Phase 6, Karachi",
    lat: 24.8009,
    lng: 67.0511,
    price: 48_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 2100,
    areaUnit: "sqft",
    areaSqft: 2100,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Well-maintained apartment in a small, low-density building in DHA Phase 6 with a covered balcony, dedicated parking and reliable lift service. Walking distance to Khayaban-e-Bukhari's restaurant and retail strip.",
    features: [
      "Corner unit with cross ventilation",
      "Covered balcony with utility space",
      "Dedicated covered parking bay",
      "Building maintained by a residents' association",
    ],
    amenities: ["Elevator", "Security guard", "Standby generator", "Water filtration"],
    images: [photos.interiors[3], photos.bedrooms[1], photos.interiors[6], photos.bedrooms[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1620,
    daysAgo: 8,
  },
  {
    slug: "shop-on-ground-floor-dha-phase-2-islamabad-rent",
    title: "Ground Floor Retail Shop on Main Boulevard",
    purpose: "rent",
    category: "shop",
    propertyType: "Shop",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 2",
    address: "Main Boulevard, DHA Phase 2, Islamabad",
    lat: 33.5385,
    lng: 73.1553,
    price: 195_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 1,
    areaValue: 600,
    areaUnit: "sqft",
    areaSqft: 600,
    parking: 2,
    furnishing: "Bare shell",
    possession: "Available",
    description:
      "Ground floor shop with 22-foot glass frontage on a high-traffic boulevard commercial in DHA Phase 2 Islamabad. Suitable for fashion retail, cafes or a pharmacy chain.",
    features: [
      "22-foot glass frontage",
      "Mezzanine staff area",
      "Separate customer washroom",
      "High footfall boulevard location",
    ],
    amenities: ["Main boulevard", "Two parking spaces", "Loading access", "Signage rights"],
    images: [photos.retail[0], photos.retail[1], photos.retail[4]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 890,
    daysAgo: 13,
  },
  {
    slug: "1-kanal-house-gulraiz-rawalpindi",
    title: "1 Kanal Family House with Basement",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "rawalpindi",
    cityName: "Rawalpindi",
    locationArea: "Gulraiz Housing Scheme",
    address: "Gulraiz Phase 5, Rawalpindi",
    lat: 33.5651,
    lng: 73.0169,
    price: 38_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 6,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 3,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Spacious 1 Kanal house in Gulraiz with a usable basement, separate guest suite and a large front lawn. A practical option for large families commuting to Islamabad daily.",
    features: [
      "Usable basement with separate entry",
      "Guest suite on ground floor",
      "Large front lawn with driveway",
      "Servant quarter at rear",
    ],
    amenities: ["Gated scheme", "Security staff", "Near expressway", "Backup power"],
    images: [photos.villas[6], photos.interiors[1], photos.bedrooms[3], photos.bedrooms[2], photos.interiors[9]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1240,
    daysAgo: 10,
  },
  {
    slug: "5-marla-house-eden-valley-faisalabad",
    title: "5 Marla Modern House in Eden Valley",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "faisalabad",
    cityName: "Faisalabad",
    locationArea: "Eden Valley",
    address: "Eden Valley, Canal Road, Faisalabad",
    lat: 31.43,
    lng: 73.05,
    price: 15_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 4,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1250,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Newly built 5 Marla house on a quiet Eden Valley street with modern elevation, tiled flooring and grey-structure-standard construction. Ready for family occupation.",
    features: [
      "Modern elevation with stone cladding",
      "Four bedrooms with attached baths",
      "Open kitchen with pantry",
      "Boundary wall with steel gate",
    ],
    amenities: ["Gated society", "Parks", "Mosque within society", "Wide streets"],
    images: [photos.villas[5], photos.interiors[5], photos.bedrooms[6], photos.bedrooms[7]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 760,
    daysAgo: 15,
  },
  {
    slug: "1-kanal-villa-buch-villas-multan",
    title: "1 Kanal Designer Villa with Pool Provision",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "multan",
    cityName: "Multan",
    locationArea: "Buch Villas",
    address: "Buch Villas, Multan",
    lat: 30.22,
    lng: 71.52,
    price: 27_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 5,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 2,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A well-proportioned villa in Buch Villas with high ceilings, a formal lounge and plumbing laid for a future pool. Buch Villas remains one of Multan's most organised addresses.",
    features: [
      "Double-height formal lounge",
      "Pool plumbing already laid",
      "Terrace garden with pergola",
      "Two-car covered parking",
    ],
    amenities: ["Gated community", "Wide roads", "Community mosque", "Backup power"],
    images: [photos.villas[7], photos.interiors[2], photos.bedrooms[4], photos.interiors[8]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 640,
    daysAgo: 18,
  },
  {
    slug: "1-kanal-house-satellite-town-gujranwala",
    title: "1 Kanal House in Satellite Town",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "gujranwala",
    cityName: "Gujranwala",
    locationArea: "Satellite Town",
    address: "Satellite Town, Gujranwala",
    lat: 32.1617,
    lng: 74.1883,
    price: 24_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 4,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Established 1 Kanal property in Satellite Town with mature trees, a large drawing room and a separate servants' block. Good bones for a renovation or an immediate family move.",
    features: [
      "Mature garden with shade trees",
      "Large drawing and dining rooms",
      "Separate servants' block",
      "Solid construction built in 2004",
    ],
    amenities: ["Near main GT Road", "Schools nearby", "Backup power", "Corner plot"],
    images: [photos.villas[2], photos.interiors[0], photos.bedrooms[5], photos.bedrooms[3]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 520,
    daysAgo: 21,
  },
  {
    slug: "house-for-rent-hayatabad-peshawar",
    title: "4 Bed House for Rent in Hayatabad",
    purpose: "rent",
    category: "house",
    propertyType: "House",
    citySlug: "peshawar",
    cityName: "Peshawar",
    locationArea: "Hayatabad",
    address: "Phase 4, Hayatabad, Peshawar",
    lat: 33.99,
    lng: 71.49,
    price: 145_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 4,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Family house for rent in Hayatabad Phase 4 with a covered car porch, small lawn and separate guest room. Suited to families or organisations needing space in the university belt.",
    features: [
      "Covered car porch",
      "Separate guest room",
      "Small front lawn",
      "Water bore plus tanker connection",
    ],
    amenities: ["Secure street", "Near hospitals and universities", "Backup power"],
    images: [photos.villas[9], photos.interiors[4], photos.bedrooms[0], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 430,
    daysAgo: 24,
  },
  {
    slug: "furnished-apartment-gulberg-lahore-rent",
    title: "Furnished Executive Apartment",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Gulberg III",
    address: "MM Alam Road, Gulberg III, Lahore",
    lat: 31.5142,
    lng: 74.3472,
    price: 425_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 4,
    areaValue: 2700,
    areaUnit: "sqft",
    areaSqft: 2700,
    parking: 2,
    furnishing: "Fully furnished",
    possession: "Available",
    description:
      "Serviced three-bedroom apartment off MM Alam Road with furniture, appliances, housekeeping and backup power included. Monthly terms are flexible for corporate and diplomatic tenants.",
    features: [
      "Complete furniture and appliance package",
      "Housekeeping twice weekly",
      "Backup generator for full load",
      "Two reserved parking bays",
      "Flexible 6 or 12 month terms",
    ],
    amenities: ["Concierge", "Gym", "Elevator", "CCTV", "Maintenance included"],
    images: [photos.interiors[8], photos.bedrooms[7], photos.interiors[9], photos.bedrooms[2]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 2010,
    daysAgo: 7,
  },
  {
    slug: "office-space-for-rent-blue-area-islamabad",
    title: "Serviced Office Suite in Blue Area",
    purpose: "rent",
    category: "office",
    propertyType: "Office",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Blue Area",
    address: "Jinnah Avenue, Blue Area, Islamabad",
    lat: 33.715,
    lng: 73.069,
    price: 650_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 3,
    areaValue: 3400,
    areaUnit: "sqft",
    areaSqft: 3400,
    parking: 6,
    furnishing: "Fitted",
    possession: "Available",
    description:
      "Fitted office suite on Jinnah Avenue with a glass façade, meeting room, server room and 40 workstations already installed. Six parking bays and 24/7 building access included.",
    features: [
      "40 workstations installed",
      "Meeting room and server room",
      "Six dedicated parking bays",
      "24/7 access with biometric entry",
    ],
    amenities: ["Blue Area location", "Central HVAC", "Lift access", "Standby power"],
    images: [photos.commercial[3], photos.commercial[8], photos.commercial[1], photos.commercial[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1330,
    daysAgo: 12,
  },
  {
    slug: "commercial-building-shahrah-e-faisal-karachi",
    title: "Multi-Floor Commercial Building",
    purpose: "buy",
    category: "building",
    propertyType: "Commercial Building",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Shahrah-e-Faisal",
    address: "Shahrah-e-Faisal, Karachi",
    lat: 24.8607,
    lng: 67.0626,
    price: 320_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 10,
    areaValue: 12000,
    areaUnit: "sqft",
    areaSqft: 12000,
    parking: 20,
    furnishing: "Fitted",
    possession: "Available",
    description:
      "Six-storey commercial building on Shahrah-e-Faisal with ground-floor retail, four office floors and a rooftop cafeteria. Currently tenanted, offering immediate rental income to a buyer.",
    features: [
      "Ground floor retail plus four office floors",
      "Currently tenanted with rental income",
      "20 parking spaces in basement and rear",
      "Two lifts with 400 KVA connection",
    ],
    amenities: ["Prime corridor", "Backup generators", "Fire and safety compliant", "Passenger lifts"],
    images: [photos.commercial[4], photos.commercial[2], photos.commercial[9], photos.commercial[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 980,
    daysAgo: 16,
  },
  {
    slug: "penthouse-clifton-block-5-karachi",
    title: "Sea-Facing Penthouse at Clifton",
    purpose: "buy",
    category: "penthouse",
    propertyType: "Penthouse",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Clifton Block 5",
    address: "Khayaban-e-Saadi, Clifton Block 5, Karachi",
    lat: 24.8138,
    lng: 67.03,
    price: 185_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 5200,
    areaUnit: "sqft",
    areaSqft: 5200,
    parking: 3,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Full-floor penthouse with a wrap-around terrace, private plunge pool and views across Clifton towards the sea. Private lift lobby and dedicated staff quarters included.",
    features: [
      "Wrap-around terrace with plunge pool",
      "Private lift lobby",
      "Staff quarters with separate access",
      "Imported kitchen and bathroom fittings",
    ],
    amenities: ["Sea views", "Swimming pool", "Gym", "Concierge", "Power backup"],
    images: [photos.interiors[7], photos.villas[8], photos.bedrooms[4], photos.interiors[5], photos.bedrooms[1]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 2450,
    daysAgo: 14,
  },
  {
    slug: "10-marla-plot-dha-phase-1-islamabad",
    title: "10 Marla Plot in DHA Phase 1",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 1",
    address: "Sector B, DHA Phase 1, Islamabad",
    lat: 33.5455,
    lng: 73.1603,
    price: 42_000_000,
    priceUnit: "total",
    negotiable: false,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "Developed plot in the established DHA Phase 1 with utilities, sewerage and roads complete. A low-risk entry into the capital's most consistent residential sector.",
    features: [
      "Fully developed sector",
      "Utilities and sewerage complete",
      "Clear title, immediate transfer",
      "Neighbouring houses already built",
    ],
    amenities: ["Gated society", "Parks", "Wide roads", "Security"],
    images: [photos.dev[5], photos.dev[1], photos.dev[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1890,
    daysAgo: 17,
  },
  {
    slug: "warehouse-for-rent-port-qasim-karachi",
    title: "Warehouse with Loading Bay — Port Qasim",
    purpose: "rent",
    category: "warehouse",
    propertyType: "Warehouse",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Port Qasim",
    address: "Port Qasim Industrial Zone, Karachi",
    lat: 24.7876,
    lng: 67.3216,
    price: 950_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 2,
    areaValue: 24000,
    areaUnit: "sqft",
    areaSqft: 24000,
    parking: 10,
    furnishing: "Bare shell",
    possession: "Available",
    description:
      "Clear-span warehouse near Port Qasim with an 8-metre clear height, two container loading bays and a fenced yard. Suitable for third-party logistics and import distribution.",
    features: [
      "8-metre clear internal height",
      "Two container loading bays",
      "Fenced container parking yard",
      "Office block of 1,200 sq ft",
    ],
    amenities: ["Container access", "24/7 security", "Industrial power", "Direct port link"],
    images: [photos.commercial[7], photos.commercial[5], photos.commercial[1]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 610,
    daysAgo: 20,
  },
  {
    slug: "2-bed-apartment-johar-town-lahore-rent",
    title: "Newly Built 2 Bed Apartment",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Johar Town",
    address: "Block J, Johar Town, Lahore",
    lat: 31.4697,
    lng: 74.2728,
    price: 95000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 2,
    bathrooms: 2,
    areaValue: 1150,
    areaUnit: "sqft",
    areaSqft: 1150,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Practical two-bedroom apartment in a new Johar Town building with tiled floors, fitted kitchen cabinets and a small balcony. Close to Expo Centre and Lahore's Ring Road access.",
    features: [
      "Fitted kitchen cabinets",
      "Balcony with utility area",
      "Standby generator in building",
      "Reserved motorcycle parking",
    ],
    amenities: ["Elevator", "Water filtration", "Security guard"],
    images: [photos.bedrooms[5], photos.interiors[1], photos.bedrooms[3]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1470,
    daysAgo: 6,
  },
  {
    slug: "shop-for-rent-liberty-market-lahore",
    title: "Retail Unit at Liberty Market",
    purpose: "rent",
    category: "shop",
    propertyType: "Shop",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Liberty Market",
    address: "Liberty Market, Gulberg, Lahore",
    lat: 31.5116,
    lng: 74.3428,
    price: 320_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 1,
    areaValue: 450,
    areaUnit: "sqft",
    areaSqft: 450,
    parking: 1,
    furnishing: "Fitted",
    possession: "Available",
    description:
      "Prime retail unit inside Liberty Market with steady walk-in traffic, air conditioning installed and signage visibility from the main corridor.",
    features: [
      "Split air conditioning installed",
      "Ceiling and rear storage area",
      "High walk-in customer traffic",
      "Corridor signage visibility",
    ],
    amenities: ["Prime retail zone", "Loading access", "Washroom", "Security"],
    images: [photos.retail[3], photos.retail[2], photos.retail[5]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 830,
    daysAgo: 19,
  },
  {
    slug: "upper-portion-for-rent-bahria-town-phase-8-rawalpindi",
    title: "Upper Portion for Rent — Bahria Town Phase 8",
    purpose: "rent",
    category: "apartment",
    propertyType: "Upper Portion",
    citySlug: "rawalpindi",
    cityName: "Rawalpindi",
    locationArea: "Bahria Town Phase 8",
    address: "Sector C, Bahria Town Phase 8, Rawalpindi",
    lat: 33.51,
    lng: 73.09,
    price: 85_000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1800,
    areaUnit: "sqft",
    areaSqft: 1800,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Independent upper portion with its own entrance, three bedrooms and a terrace, in a low-traffic sector of Bahria Town Phase 8. Ideal for a small family or a working couple.",
    features: [
      "Independent entrance and staircase",
      "Private terrace",
      "Three bedrooms with attached baths",
      "Separate electricity meter",
    ],
    amenities: ["Gated community", "Security", "Parks nearby", "Shuttle service"],
    images: [photos.interiors[6], photos.bedrooms[2], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 700,
    daysAgo: 22,
  },
  {
    slug: "marla-plot-dha-multan",
    title: "1 Kanal Plot in DHA Multan",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "multan",
    cityName: "Multan",
    locationArea: "DHA Multan",
    address: "Sector A, DHA Multan",
    lat: 30.16,
    lng: 71.46,
    price: 21_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "Balloted 1 Kanal plot in DHA Multan Sector A with development underway and clear instalment record. A longer-horizon option in South Punjab's most credible new society.",
    features: [
      "Balloted file with complete receipts",
      "Instalments up to date",
      "Development ongoing in sector",
      "Clear transfer procedure",
    ],
    amenities: ["Gated society", "DHA infrastructure", "Parks planned", "Security"],
    images: [photos.dev[0], photos.dev[6], photos.dev[2]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 1110,
    daysAgo: 25,
  },
];

export const projectSeed = [
  {
    slug: "the-grand-residences",
    name: "The Grand Residences",
    developer: "Northline Developments",
    cityName: "Islamabad",
    citySlug: "islamabad",
    location: "DHA Phase 2, Islamabad",
    projectType: "Luxury Apartments",
    status: "Booking Open",
    startingPrice: 19_000_000,
    completion: "Handover Q4 2027",
    units: "1, 2 and 3 bed apartments · 320 units",
    description:
      "Two towers arranged around landscaped courtyards in DHA Phase 2, with a residents' club, retail arcade and Margalla views from upper floors. Payment plans spread over 36 months with a 25% down payment.",
    highlights: [
      "36-month instalment plan",
      "Residents' club, gym and pool",
      "Smart access control and CCTV",
      "Retail arcade and clinic space on site",
    ],
    images: [photos.interiors[7], photos.commercial[1], photos.interiors[9], photos.bedrooms[2]],
    lat: 33.532,
    lng: 73.1496,
    featured: true,
  },
  {
    slug: "bahria-heights-karachi",
    name: "Bahria Heights",
    developer: "Bahria Town",
    cityName: "Karachi",
    citySlug: "karachi",
    location: "Precinct 10A, Bahria Town Karachi",
    projectType: "High-Rise Apartments",
    status: "Under Construction",
    startingPrice: 12_500_000,
    completion: "Handover Q2 2027",
    units: "Studio, 1 and 2 bed · 480 units",
    description:
      "A 24-storey residential tower with serviced apartments, a shared pool deck and direct access to Bahria Town's commercial boulevard. Suited to investors targeting the city's rental market.",
    highlights: [
      "Pool deck and sky lounge",
      "Serviced apartment management option",
      "Studio to 2-bed configurations",
      "Close to commercial boulevard",
    ],
    images: [photos.commercial[3], photos.interiors[0], photos.bedrooms[7], photos.interiors[3]],
    lat: 25.0007,
    lng: 67.3142,
    featured: true,
  },
  {
    slug: "estate-wx-greens-lahore",
    name: "Greens Enclave",
    developer: "Greens Enclave (Pvt) Ltd",
    cityName: "Lahore",
    citySlug: "lahore",
    location: "Main Bedian Road, Lahore",
    projectType: "Housing Scheme",
    status: "Launching",
    startingPrice: 7_200_000,
    completion: "Possession from 2027",
    units: "5 and 10 Marla residential plots",
    description:
      "A gated housing scheme on Bedian Road offering 5 and 10 Marla plots with a phased development plan, underground utilities and a commercial belt on the main entrance.",
    highlights: [
      "5 and 10 Marla plots",
      "Underground utilities planned",
      "Entry-level pricing with instalment plan",
      "Commercial belt at main entrance",
    ],
    images: [photos.dev[5], photos.dev[1], photos.dev[0], photos.dev[6]],
    lat: 31.4869,
    lng: 74.4563,
    featured: true,
  },
  {
    slug: "clifton-harbour-towers",
    name: "Clifton Harbour Towers",
    developer: "Meridian Estates",
    cityName: "Karachi",
    citySlug: "karachi",
    location: "Clifton Block 5, Karachi",
    projectType: "Luxury Apartments",
    status: "Ready to Move",
    startingPrice: 62_000_000,
    completion: "Ready — occupied tower",
    units: "3 and 4 bed sea-facing apartments",
    description:
      "Occupied luxury tower in Clifton Block 5 with limited resale inventory, sea-facing balconies, private lift lobbies and a fully fitted amenity floor.",
    highlights: [
      "Sea-facing balconies",
      "Private lift lobbies",
      "Amenity floor with pool and gym",
      "Limited resale availability",
    ],
    images: [photos.interiors[7], photos.bedrooms[1], photos.interiors[5], photos.bedrooms[4]],
    lat: 24.8138,
    lng: 67.03,
    featured: false,
  },
  {
    slug: "eden-valley-phase-3",
    name: "Eden Valley Phase 3",
    developer: "Eden Builders",
    cityName: "Faisalabad",
    citySlug: "faisalabad",
    location: "Canal Road, Faisalabad",
    projectType: "Housing Scheme",
    status: "Under Development",
    startingPrice: 5_400_000,
    completion: "Development by 2027",
    units: "5 Marla houses and plots",
    description:
      "The third phase of Eden Valley with built-up and plot options, delivered infrastructure and a location linked to Faisalabad's Canal Road corridor.",
    highlights: [
      "Built-up houses available",
      "Infrastructure work underway",
      "Flexible 24-month plan",
      "Growing rental demand nearby",
    ],
    images: [photos.dev[4], photos.dev[3], photos.dev[5], photos.dev[0]],
    lat: 31.43,
    lng: 73.05,
    featured: false,
  },
  {
    slug: "dha-multan-sector-overview",
    name: "DHA Multan Sector A",
    developer: "Defence Housing Authority",
    cityName: "Multan",
    citySlug: "multan",
    location: "DHA Multan, Multan",
    projectType: "Mixed Development",
    status: "Under Development",
    startingPrice: 18_500_000,
    completion: "Phased possession",
    units: "5, 10 Marla and 1 Kanal plots",
    description:
      "Residential plots in DHA Multan's developed Sector A with trunk infrastructure complete, plus a commercial belt along the sector's main road.",
    highlights: [
      "Trunk infrastructure complete",
      "DHA-managed security and maintenance",
      "Commercial belt frontage available",
      "Established resale market",
    ],
    images: [photos.dev[6], photos.dev[5], photos.dev[1], photos.dev[2]],
    lat: 30.16,
    lng: 71.46,
    featured: false,
  },
];

export const postSeed = [
  {
    slug: "best-areas-to-buy-property-in-lahore",
    title: "Best Areas to Buy Property in Lahore in 2026",
    category: "Market Insight",
    excerpt:
      "A practical breakdown of DHA, Bahria Town, Gulberg and Johar Town — budgets, buyer profile, rental demand and what each area delivers for end users versus investors.",
    body: [
      "Lahore's housing market rewards buyers who understand the difference between a developed sector and a growing one. DHA phases carry the highest entry cost but also the most consistent resale activity, which matters if your plan is to exit within three to five years.",
      "Bahria Town Lahore offers a lower entry point with a complete, self-contained lifestyle: schools, hospitals, commercial zones and its own security infrastructure. The trade-off is distance from central Lahore and a dependence on society management quality.",
      "Gulberg III and Gulberg II remain unmatched for buyers who want walkable access to business districts, universities and restaurants. Expect a premium for smaller plots and older construction that often needs renovation.",
      "Johar Town and Wapda Town suit families on structured budgets. Prices are more predictable, inventory is larger, and the Ring Road link makes commuting to other parts of the city practical.",
      "For any purchase, verify the transfer record with the society or a legal advisor, confirm dues clearance in writing, and inspect the property during working hours. These three steps avoid most disputes we see in practice.",
    ],
    author: "Pak Property Research",
    readMinutes: 7,
    tags: ["Lahore", "Buying Guide", "DHA", "Bahria Town"],
    image: photos.cities.lahore,
  },
  {
    slug: "property-investment-islamabad-guide",
    title: "Property Investment in Islamabad: What Actually Drives Value",
    category: "Investment",
    excerpt:
      "Sector planning, embassy zones, rental demand from institutions and the supply pipeline — the factors that shape Islamabad property values over a five-year horizon.",
    body: [
      "Islamabad's value is driven largely by deliberate planning. Sector grids, green belts, regulated commercial zones and predictable municipal services keep the capital's premium stable compared with cities that expand informally.",
      "Rental demand here is institutional. Diplomatic missions, development sector organisations, universities and hospitals rent apartments and houses for long tenures, which supports yields in sectors close to Blue Area, F-11, G-11 and DHA.",
      "New development in DHA Islamabad and Bahria Enclave has expanded the supply of standalone houses. For investors, plots generally deliver smoother capital appreciation while constructed houses deliver better rental income.",
      "Watch the payment plan. Instalment-based projects can be attractive on entry, but the discount you negotiate on a cash purchase is often larger than the plan's headline pricing.",
      "Diversification across plot, apartment and commercial exposure remains the most durable approach in any single city, including Islamabad.",
    ],
    author: "Ayesha Noor",
    readMinutes: 6,
    tags: ["Islamabad", "Investment", "DHA"],
    image: photos.cities.islamabad,
  },
  {
    slug: "dha-vs-bahria-town-comparison",
    title: "DHA vs Bahria Town: How to Choose",
    category: "Buying Guide",
    excerpt:
      "A side-by-side comparison of pricing, transfer procedure, maintenance costs, security, amenities and resale behaviour between Pakistan's two most recognised developers.",
    body: [
      "DHA is known for stricter building controls, disciplined development timelines and a highly liquid resale market. That discipline shows in resale price stability and in how confident buyers feel about transfer procedures.",
      "Bahria Town prioritises scale and lifestyle. You generally pay less per Marla for access to parks, themed commercial areas, schools and internal transport, though society charges and maintenance levies recur throughout ownership.",
      "If your priority is capital preservation with a future exit, DHA tends to be the more predictable choice. If your priority is affordability, immediate occupancy and amenities, Bahria Town often fits better.",
      "In both cases, ask for the complete dues statement, confirm the transfer procedure in writing, and understand the timeline before paying any token amount. Documentation quality is the single biggest differentiator between a comfortable transaction and a difficult one.",
    ],
    author: "Pak Property Research",
    readMinutes: 5,
    tags: ["DHA", "Bahria Town", "Comparison"],
    image: photos.cities.lahoreAlt,
  },
  {
    slug: "commercial-property-investment-pakistan",
    title: "Commercial Property Investment: Offices, Retail and Warehousing",
    category: "Commercial",
    excerpt:
      "Commercial assets typically price differently from residential — here is how to evaluate tenants, lease structures, footfall and yield before committing capital.",
    body: [
      "Commercial property is valued by the income it can produce. Before looking at price, establish achievable rent, typical lease length and the cost of making a unit tenant-ready.",
      "Retail works on footfall and visibility. Ground floor units on a main boulevard with glass frontage command a premium that is usually justified — but only where parking is available and signage rights are clear.",
      "Offices are driven by location prestige and building services. Reliable backup power, central cooling, lift redundancy and secure parking decide whether a tenant signs for three years or one.",
      "Warehousing and logistics demand clear height, container access and proximity to arteries such as the M-2 or Port Qasim. Yield is often higher, but so is tenant concentration risk with a single occupier.",
      "Finally, model the full carrying cost: maintenance, society charges, municipal taxes and vacancy between tenants. Net yield, not gross rent, is what compounds.",
    ],
    author: "Bilal Shaikh",
    readMinutes: 6,
    tags: ["Commercial", "Office", "Retail", "Investment"],
    image: photos.commercial[0],
  },
  {
    slug: "rental-property-guide-pakistan",
    title: "A Practical Rental Property Guide for Landlords",
    category: "Rental Guide",
    excerpt:
      "How to price a unit, screen tenants, structure agreements and keep occupancy high without sacrificing maintenance standards.",
    body: [
      "Rental pricing follows evidence, not sentiment. Compare three to five genuinely similar units in the same society, then adjust for floor, furnishing, parking and views. An overpriced unit that sits vacant for two months usually costs more than a slightly lower rent agreed in one week.",
      "Screening protects the asset. Confirm employment or business documentation, verify the previous tenancy if possible, and always complete a written agreement that states notice periods and utility responsibility clearly.",
      "Furnished and serviced units earn more per square foot in Pakistan's larger cities, but only where management is professional. Housekeeping, appliance replacement and faster turnover all need to be budgeted.",
      "Keep a maintenance reserve equal to roughly one month's rent per year. It removes the temptation to delay small repairs, which is the most common reason tenants leave good units.",
    ],
    author: "Pak Property Research",
    readMinutes: 5,
    tags: ["Rental", "Landlord", "Yield"],
    image: photos.interiors[9],
  },
  {
    slug: "buying-property-in-pakistan-checklist",
    title: "Buying Property in Pakistan: A Documentation Checklist",
    category: "Guides",
    excerpt:
      "Title verification, NOC checks, dues clearance, transfer letters and registration steps — the paperwork sequence that protects a property purchase.",
    body: [
      "Start with the title. Request the allotment letter, transfer letter, previous chain of transfers and the society's NOC where applicable. For plots in private schemes, confirm the scheme is approved by the relevant development authority.",
      "Verify dues. Obtain a written dues statement from the society or authority that shows all charges cleared up to the date of transfer, and confirm whether any development charges remain payable.",
      "Draft the agreement precisely. The agreement should record the property description, exact price, payment schedule, possession date, and the responsibility for transfer fees and taxes.",
      "Complete the transfer at the society office in the presence of both parties or their authorised representatives, and keep certified copies of every document you sign.",
      "For high-value transactions, engage a lawyer experienced in property matters in that specific city. Documentation quality is what protects both the buyer and the seller.",
    ],
    author: "Pak Property Research",
    readMinutes: 6,
    tags: ["Buying Guide", "Documentation", "Legal"],
    image: photos.dev[7],
  },
];

export const testimonialSeed = [
  {
    name: "Kamran Tariq",
    role: "Overseas buyer, Dubai",
    city: "Lahore",
    quote:
      "An overseas buyer compares three sample DHA Phase 5 houses using area briefs and the mortgage calculator, narrowing the decision down to a single viewing trip.",
    rating: 5,
    initials: "KT",
    sortOrder: 1,
  },
  {
    name: "Dr. Farah Siddiqui",
    role: "First-time buyer",
    city: "Islamabad",
    quote:
      "A first-time buyer filters sample listings by budget and size, then follows the documentation checklist to understand what a real purchase would require.",
    rating: 5,
    initials: "FS",
    sortOrder: 2,
  },
  {
    name: "Imran Yousaf",
    role: "Retail chain expansion lead",
    city: "Karachi",
    quote:
      "A retail expansion lead lines up three sample commercial units by frontage, footfall notes and rent to prepare a shortlist review.",
    rating: 5,
    initials: "IY",
    sortOrder: 3,
  },
  {
    name: "Hina Bhatti",
    role: "Landlord, 4 rental units",
    city: "Lahore",
    quote:
      "A landlord models post-renovation rent for four sample Johar Town units with the rental-yield calculator before setting asking prices.",
    rating: 4,
    initials: "HB",
    sortOrder: 4,
  },
  {
    name: "Ahsan Qureshi",
    role: "Investor",
    city: "Multan",
    quote:
      "An investor compares sample DHA Multan and Buch Villas options side by side using the same filters and payment figures.",
    rating: 5,
    initials: "AQ",
    sortOrder: 5,
  },
  {
    name: "Sadia Rehman",
    role: "Family relocation",
    city: "Rawalpindi",
    quote:
      "A relocating family shortlists sample areas by school, hospital and park proximity before planning any visits.",
    rating: 5,
    initials: "SR",
    sortOrder: 6,
  },
];
